apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: default
  labels:
    app: secure-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      # Security: Ensure the pod runs with the specific user ID defined in the Dockerfile
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: secure-app
          # Image placeholder - GitHub Actions will replace this tag during CI/CD
          image: agslima/secure-fullstack-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
          # Security: Hardening the container runtime
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL # Drop all Linux capabilities (Ping, Chown, etc.)

          # Reliability: Health Checks
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          # Reliability: Resource Quotas (Prevent Resource Exhaustion Attacks)
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: secure-app-service
spec:
  type: ClusterIP # Use LoadBalancer if you want external access immediately
  selector:
    app: secure-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
